Optional logger
microsoft/ObjectStoreProvider pull request #53
Opened 2023-08-16 00:41 UTC by danielmsft

Adds an additional parameter to pass in an arbitrary logger to optionally use instead of browser console, if logger isn't provided it uses the browser console

This is backwards compatible.

2023-08-16 17:30 UTC, thomastay reviewed
Can we do this for the inMemoryProvider too?

2023-08-16 18:40 UTC, danielmsft commented
> Can we do this for the inMemoryProvider too?

I was going to but I didn't see any logs in that file, so it would just be an unused variable that the linter would complain about

2023-08-16 19:02 UTC, danielmsft commented
It only warns about the private field, should I still add without the private field?

2023-08-16 23:18 UTC, M1Les commented
> > Can we do this for the inMemoryProvider too?
> 
> I was going to but I didn't see any logs in that file, so it would just be an unused variable that the linter would complain about

We might use it in the future, though.

2023-08-28 19:20 UTC, thomastay approved these changes

2023-08-28 19:20 UTC, thomastay commented on src/InMemoryProvider.ts
> +// Very simple in-memory dbprovider for handling IE inprivate windows (and unit tests, maybe?)
[nit] Since we are changing this comment, can we remove the part about IE inprivate windows and unit tests? We now use it all the time

2023-08-28 21:10 UTC, M1Les requested changes

2023-08-28 21:10 UTC, M1Les commented on src/ObjectStoreProviderUtils.ts
> +export interface Logger {
Nit: Can we please move this to ObjectStoreProvider.ts where all interfaces are defined?

2023-08-28 21:43 UTC, danielmsft commented on src/InMemoryProvider.ts
> +// Very simple in-memory dbprovider for handling IE inprivate windows (and unit tests, maybe?)
just removed the comment, didn't see that there was any substance there

2023-08-28 21:44 UTC, danielmsft commented on src/ObjectStoreProviderUtils.ts
> +export interface Logger {
much better, thanks!

2023-08-28 21:44 UTC, danielmsft commented on src/IndexedDbProvider.ts
> +type Logger = {
updated

2023-08-28 22:19 UTC, M1Les approved these changes

2023-08-28 22:20 UTC, merged