Improve InMemoryProvider getRange function from O(N^2) to O(N)
microsoft/ObjectStoreProvider pull request #62
Opened 2024-09-05 19:50 UTC by bhargeymehta

I noticed that in the getRange function we're doing a O(N^2) operation when constructing the results array. This time complexity arises because of doing a concat of 2 arrays instead of doing push operations on a single array.

2024-09-05 22:11 UTC, thomastay requested changes
Other than the comment, lgtm, but please wait for other folks on my team to take a look as well before merging

2024-09-05 22:11 UTC, thomastay commented on src/InMemoryProvider.ts
> +          const pushToResult = (v: ItemType) => values.push(v);
As `values` is no longer mutated, we should change it to be `const`

2024-09-05 22:12 UTC, thomastay commented
Can you also bump the patch version in the package.json

2024-09-06 04:48 UTC, bhargeymehta commented on src/InMemoryProvider.ts
> +          const pushToResult = (v: ItemType) => values.push(v);
changed to const

2024-09-06 04:50 UTC, bhargeymehta commented
@microsoft-github-policy-service agree company="Microsoft"

2024-09-06 04:50 UTC, bhargeymehta commented
> Can you also bump the patch version in the package.json

done

2024-09-09 17:16 UTC, eliranek1 approved these changes

2024-09-09 17:26 UTC, thomastay approved these changes

2024-09-09 18:40 UTC, M1Les approved these changes

2024-09-09 18:40 UTC, merged